### ISSUE TITLE
provide a docker-compose file

### ISSUE THREAD

**Issue by leizhiyuan** [apache/rocketmq-docker#100]
so users can run in local machine quickly

@zzjcool

**Comment by leizhiyuan** [comment]
ref https://github.com/apache/rocketmq-docker/issues/95

**Comment by zzjcool** [comment]
I will add the docker-compose file

**Comment by leizhiyuan** [comment]
Expected Execution

"sh play-docker-compose.sh" will start namesvr and broker as before.

"sh play-docker-compose.sh proxy" will start namesvr, broker, and proxy.

**Comment by leizhiyuan** [comment]
thanks @zzjcool  

test ok
https://github.com/apache/rocketmq-docker/pull/101#issuecomment-1956013568
https://github.com/apache/rocketmq-docker/pull/101#issuecomment-1956005579
