### ISSUE TITLE
Building ARM version image, script execution failed

### ISSUE THREAD

**Issue by MagicGopher** [apache/rocketmq-docker#107]
Problem description.
The build script execution failed, and the terminal information is as follows:
```
> sh build-image.sh 4.9.8 centos
Version = 4.9.8
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  35.84kB
Step 1/23 : FROM eclipse-temurin:8-jdk-centos7 AS builder
8-jdk-centos7: Pulling from library/eclipse-temurin
6717b8ec66cd: Pull complete
3e8872ff80c9: Pull complete
c3fb8a2564dd: Pull complete
9653d55c1418: Pull complete
27cfe16a1faa: Pull complete
Digest: sha256:1b94e6658b77b42f3d8d5ccc2ffda12afbbcd73943bcd16b0b49b5abe700ed1f
Status: Downloaded newer image for eclipse-temurin:8-jdk-centos7
 ---> 360e0ad6bba7
Step 2/23 : ARG version
 ---> Running in 5bc5d1cf6d5a
 ---> Removed intermediate container 5bc5d1cf6d5a
 ---> e0ff1cb39522
Step 3/23 : RUN set -eux     && yum -y update     && yum -y install curl gnupg unzip     && yum clean all -y
 ---> Running in baa4e5b356be
+ yum -y update
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=aarch64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/aarch64
The command '/bin/sh -c set -eux     && yum -y update     && yum -y install curl gnupg unzip     && yum clean all -y' returned a non-zero code: 1
```
How can I solve this problem? Should I replace yum with apt? And then replace eclipse-temurin:8-jdk-centos7 with openjdk?

**Comment by MagicGopher** [comment]
> I get the same problem

I added a Dockerfile-ubuntu, replaced yum with apt-get, changed jdk to arm64v8/ubuntu:20.04, and successfully built the arm version of rocketmq

![QQ20240710-203219](https://github.com/apache/rocketmq-docker/assets/50815770/8e6a4b49-0472-42d8-a87b-2919c8e92962)

**Comment by seart** [comment]
Can you explain the operation steps in detail? 

> > I get the same problem
> 
> I added a Dockerfile-ubuntu, replaced yum with apt-get, changed jdk to arm64v8/ubuntu:20.04, and successfully built the arm version of rocketmq
> 
> ![QQ20240710-203219](https://private-user-images.githubusercontent.com/50815770/347399897-8e6a4b49-0472-42d8-a87b-2919c8e92962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzY0NDUsIm5iZiI6MTcyMDc3NjE0NSwicGF0aCI6Ii81MDgxNTc3MC8zNDczOTk4OTctOGU2YTRiNDktMDQ3Mi00MmQ4LWE4N2ItMjkxOWM4ZTkyOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWY2N2NjNTdmYmYwYjMzYzU1ZmQyZTExOGU4NTExNjI2NWEyNjhlMWNlMTU3YjllNmQ1YjNmMzEwYThiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXUdFx8d655epZe8Yj4864eYiubxvpwv9lOjFh7MKws)

**Comment by caigy** [comment]
CentOS 7 reached the End of Maintenance on June 30, 2024. As a result, we have to adapt a new base image to replace CentOS 7.

**Comment by MagicGopher** [comment]
> CentOS 7 reached the End of Maintenance on June 30, 2024. As a result, we have to adapt a new base image to replace CentOS 7.

Yes, then I changed yum to apt-get and the container image to arm64v8/ubuntu:20.04 to build the arm version of the rocketmq image.

**Comment by MagicGopher** [comment]
> Can I see your Dockerfile-ubuntu file content? build-image.sh file only centos or alpine two options , it should add ubuntu Options right? <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/13324413/348215170-cd0c5043-9122-4951-b4cf-fc0c3a27894f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODI3MDEsIm5iZiI6MTcyMDc4MjQwMSwicGF0aCI6Ii8xMzMyNDQxMy8zNDgyMTUxNzAtY2QwYzUwNDMtOTEyMi00OTUxLWI0Y2YtZmMwYzNhMjc4OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTU1Y2FjYTE1MmJmN2QzNThlMmJjMTk3NjQ5YzVlYmNhMDc3MDlmNzM3M2E0MTU0M2VhYjNmYTM5N2UxNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbgWouCUZwBuMj1t-fTgKCKojwrDl5x5ymcWQZz94yc">
> 
> > > I get the same problem
> > 
> > 
> > I added a Dockerfile-ubuntu, replaced yum with apt-get, changed jdk to arm64v8/ubuntu:20.04, and successfully built the arm version of rocketmq
> > ![QQ20240710-203219](https://private-user-images.githubusercontent.com/50815770/347399897-8e6a4b49-0472-42d8-a87b-2919c8e92962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzY0NDUsIm5iZiI6MTcyMDc3NjE0NSwicGF0aCI6Ii81MDgxNTc3MC8zNDczOTk4OTctOGU2YTRiNDktMDQ3Mi00MmQ4LWE4N2ItMjkxOWM4ZTkyOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWY2N2NjNTdmYmYwYjMzYzU1ZmQyZTExOGU4NTExNjI2NWEyNjhlMWNlMTU3YjllNmQ1YjNmMzEwYThiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXUdFx8d655epZe8Yj4864eYiubxvpwv9lOjFh7MKws)

I did not modify the build-image.sh file. I directly modified the Dockerfile-centos file and replaced the yun source with apt-get, and changed the FROM image from: eclipse-temurin:8-jdk-centos7 AS builder to FROM arm64v8/ubuntu:20.04 AS builder. Then I built it using: sh build-image.sh version centos.

**Comment by MagicGopher** [comment]
> Can I see your Dockerfile-ubuntu file content? build-image.sh file only centos or alpine two options , it should add ubuntu Options right? <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/13324413/348215170-cd0c5043-9122-4951-b4cf-fc0c3a27894f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODI3MDEsIm5iZiI6MTcyMDc4MjQwMSwicGF0aCI6Ii8xMzMyNDQxMy8zNDgyMTUxNzAtY2QwYzUwNDMtOTEyMi00OTUxLWI0Y2YtZmMwYzNhMjc4OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTU1Y2FjYTE1MmJmN2QzNThlMmJjMTk3NjQ5YzVlYmNhMDc3MDlmNzM3M2E0MTU0M2VhYjNmYTM5N2UxNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbgWouCUZwBuMj1t-fTgKCKojwrDl5x5ymcWQZz94yc">
> 
> > > I get the same problem
> > 
> > 
> > I added a Dockerfile-ubuntu, replaced yum with apt-get, changed jdk to arm64v8/ubuntu:20.04, and successfully built the arm version of rocketmq
> > ![QQ20240710-203219](https://private-user-images.githubusercontent.com/50815770/347399897-8e6a4b49-0472-42d8-a87b-2919c8e92962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzY0NDUsIm5iZiI6MTcyMDc3NjE0NSwicGF0aCI6Ii81MDgxNTc3MC8zNDczOTk4OTctOGU2YTRiNDktMDQ3Mi00MmQ4LWE4N2ItMjkxOWM4ZTkyOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWY2N2NjNTdmYmYwYjMzYzU1ZmQyZTExOGU4NTExNjI2NWEyNjhlMWNlMTU3YjllNmQ1YjNmMzEwYThiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXUdFx8d655epZe8Yj4864eYiubxvpwv9lOjFh7MKws)

Here is my modified Dockerfile-centos file content:

FROM arm64v8/ubuntu:20.04 AS builder

ARG version

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux \
    && apt-get update \
    && apt-get install -y curl gnupg unzip openjdk-8-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L https://archive.apache.org/dist/rocketmq/${version}/rocketmq-all-${version}-bin-release.zip -o rocketmq.zip \
    && curl -L https://archive.apache.org/dist/rocketmq/${version}/rocketmq-all-${version}-bin-release.zip.asc -o rocketmq.zip.asc \
    && curl -L https://www.apache.org/dist/rocketmq/KEYS -o KEYS \
    && gpg --import KEYS \
    && gpg --batch --verify rocketmq.zip.asc rocketmq.zip

RUN unzip rocketmq.zip \
    && mkdir -p /tmp/rocketmq-${version} \
    && mv rocketmq*/* /tmp/rocketmq-${version}

# Build stage 2:
FROM arm64v8/ubuntu:20.04

ARG user=rocketmq
ARG group=rocketmq
ARG uid=3000
ARG gid=3000

ARG version

ENV DEBIAN_FRONTEND=noninteractive
ENV ROCKETMQ_VERSION ${version}
ENV ROCKETMQ_HOME /home/rocketmq/rocketmq-${ROCKETMQ_VERSION}
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64

EXPOSE 9876 10909 10911 10912

RUN groupadd -g ${gid} ${group} \
    && useradd -l -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
    && apt-get update \
    && apt-get install -y openjdk-8-jdk less openssl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/ ${ROCKETMQ_HOME}/bin/
COPY --from=builder --chown=${uid}:${gid} /tmp/rocketmq-${version}/ ${ROCKETMQ_HOME}

RUN mv ${ROCKETMQ_HOME}/bin/runserver-customize.sh ${ROCKETMQ_HOME}/bin/runserver.sh \
    && mv ${ROCKETMQ_HOME}/bin/runbroker-customize.sh ${ROCKETMQ_HOME}/bin/runbroker.sh \
    && chmod -R a+x ${ROCKETMQ_HOME}/bin/ \
    && export JAVA_OPT=" -Duser.home=/opt" \
    && sed -i 's/${JAVA_HOME}\/jre\/lib\/ext/${JAVA_HOME}\/jre\/lib\/ext:${JAVA_HOME}\/lib\/ext/' ${ROCKETMQ_HOME}/bin/tools.sh \
    && chown -R ${uid}:${gid} ${ROCKETMQ_HOME}

USER ${user}

WORKDIR ${ROCKETMQ_HOME}/bin

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["dummy"]

**Comment by MagicGopher** [comment]
> Can I see your Dockerfile-ubuntu file content? build-image.sh file only centos or alpine two options , it should add ubuntu Options right? <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/13324413/348215170-cd0c5043-9122-4951-b4cf-fc0c3a27894f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODI3MDEsIm5iZiI6MTcyMDc4MjQwMSwicGF0aCI6Ii8xMzMyNDQxMy8zNDgyMTUxNzAtY2QwYzUwNDMtOTEyMi00OTUxLWI0Y2YtZmMwYzNhMjc4OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTU1Y2FjYTE1MmJmN2QzNThlMmJjMTk3NjQ5YzVlYmNhMDc3MDlmNzM3M2E0MTU0M2VhYjNmYTM5N2UxNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbgWouCUZwBuMj1t-fTgKCKojwrDl5x5ymcWQZz94yc">
> 
> > > I get the same problem
> > 
> > 
> > I added a Dockerfile-ubuntu, replaced yum with apt-get, changed jdk to arm64v8/ubuntu:20.04, and successfully built the arm version of rocketmq
> > ![QQ20240710-203219](https://private-user-images.githubusercontent.com/50815770/347399897-8e6a4b49-0472-42d8-a87b-2919c8e92962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzY0NDUsIm5iZiI6MTcyMDc3NjE0NSwicGF0aCI6Ii81MDgxNTc3MC8zNDczOTk4OTctOGU2YTRiNDktMDQ3Mi00MmQ4LWE4N2ItMjkxOWM4ZTkyOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWY2N2NjNTdmYmYwYjMzYzU1ZmQyZTExOGU4NTExNjI2NWEyNjhlMWNlMTU3YjllNmQ1YjNmMzEwYThiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXUdFx8d655epZe8Yj4864eYiubxvpwv9lOjFh7MKws)

Here is my modified Dockerfile-centos file content:

FROM arm64v8/ubuntu:20.04 AS builder

ARG version

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux \
    && apt-get update \
    && apt-get install -y curl gnupg unzip openjdk-8-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L https://archive.apache.org/dist/rocketmq/${version}/rocketmq-all-${version}-bin-release.zip -o rocketmq.zip \
    && curl -L https://archive.apache.org/dist/rocketmq/${version}/rocketmq-all-${version}-bin-release.zip.asc -o rocketmq.zip.asc \
    && curl -L https://www.apache.org/dist/rocketmq/KEYS -o KEYS \
    && gpg --import KEYS \
    && gpg --batch --verify rocketmq.zip.asc rocketmq.zip

RUN unzip rocketmq.zip \
    && mkdir -p /tmp/rocketmq-${version} \
    && mv rocketmq*/* /tmp/rocketmq-${version}

FROM arm64v8/ubuntu:20.04

ARG user=rocketmq
ARG group=rocketmq
ARG uid=3000
ARG gid=3000

ARG version

ENV DEBIAN_FRONTEND=noninteractive
ENV ROCKETMQ_VERSION ${version}
ENV ROCKETMQ_HOME /home/rocketmq/rocketmq-${ROCKETMQ_VERSION}
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64

EXPOSE 9876 10909 10911 10912

RUN groupadd -g ${gid} ${group} \
    && useradd -l -u ${uid} -g ${gid} -m -s /bin/bash ${user} \
    && apt-get update \
    && apt-get install -y openjdk-8-jdk less openssl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/ ${ROCKETMQ_HOME}/bin/
COPY --from=builder --chown=${uid}:${gid} /tmp/rocketmq-${version}/ ${ROCKETMQ_HOME}

RUN mv ${ROCKETMQ_HOME}/bin/runserver-customize.sh ${ROCKETMQ_HOME}/bin/runserver.sh \
    && mv ${ROCKETMQ_HOME}/bin/runbroker-customize.sh ${ROCKETMQ_HOME}/bin/runbroker.sh \
    && chmod -R a+x ${ROCKETMQ_HOME}/bin/ \
    && export JAVA_OPT=" -Duser.home=/opt" \
    && sed -i 's/${JAVA_HOME}\/jre\/lib\/ext/${JAVA_HOME}\/jre\/lib\/ext:${JAVA_HOME}\/lib\/ext/' ${ROCKETMQ_HOME}/bin/tools.sh \
    && chown -R ${uid}:${gid} ${ROCKETMQ_HOME}

USER ${user}

WORKDIR ${ROCKETMQ_HOME}/bin

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["dummy"]

**Comment by seart** [comment]
> > Can I see your Dockerfile-ubuntu file content? build-image.sh file only centos or alpine two options , it should add ubuntu Options right? <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/13324413/348215170-cd0c5043-9122-4951-b4cf-fc0c3a27894f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODI3MDEsIm5iZiI6MTcyMDc4MjQwMSwicGF0aCI6Ii8xMzMyNDQxMy8zNDgyMTUxNzAtY2QwYzUwNDMtOTEyMi00OTUxLWI0Y2YtZmMwYzNhMjc4OTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExMDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTU1Y2FjYTE1MmJmN2QzNThlMmJjMTk3NjQ5YzVlYmNhMDc3MDlmNzM3M2E0MTU0M2VhYjNmYTM5N2UxNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbgWouCUZwBuMj1t-fTgKCKojwrDl5x5ymcWQZz94yc">
> > > > I get the same problem
> > > 
> > > 
> > > I added a Dockerfile-ubuntu, replaced yum with apt-get, changed jdk to arm64v8/ubuntu:20.04, and successfully built the arm version of rocketmq
> > > ![QQ20240710-203219](https://private-user-images.githubusercontent.com/50815770/347399897-8e6a4b49-0472-42d8-a87b-2919c8e92962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzY0NDUsIm5iZiI6MTcyMDc3NjE0NSwicGF0aCI6Ii81MDgxNTc3MC8zNDczOTk4OTctOGU2YTRiNDktMDQ3Mi00MmQ4LWE4N2ItMjkxOWM4ZTkyOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNWY2N2NjNTdmYmYwYjMzYzU1ZmQyZTExOGU4NTExNjI2NWEyNjhlMWNlMTU3YjllNmQ1YjNmMzEwYThiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXUdFx8d655epZe8Yj4864eYiubxvpwv9lOjFh7MKws)
> 
> Here is my modified Dockerfile-centos file content:
> 
> FROM arm64v8/ubuntu:20.04 AS builder
> 
> ARG version
> 
> ENV DEBIAN_FRONTEND=noninteractive
> 
> RUN set -eux && apt-get update && apt-get install -y curl gnupg unzip openjdk-8-jdk && apt-get clean && rm -rf /var/lib/apt/lists/*
> 
> RUN curl -L [https://archive.apache.org/dist/rocketmq/${version}/rocketmq-all-${version}-bin-release.zip](https://archive.apache.org/dist/rocketmq/$%7Bversion%7D/rocketmq-all-$%7Bversion%7D-bin-release.zip) -o rocketmq.zip && curl -L [https://archive.apache.org/dist/rocketmq/${version}/rocketmq-all-${version}-bin-release.zip.asc](https://archive.apache.org/dist/rocketmq/$%7Bversion%7D/rocketmq-all-$%7Bversion%7D-bin-release.zip.asc) -o rocketmq.zip.asc && curl -L https://www.apache.org/dist/rocketmq/KEYS -o KEYS && gpg --import KEYS && gpg --batch --verify rocketmq.zip.asc rocketmq.zip
> 
> RUN unzip rocketmq.zip && mkdir -p /tmp/rocketmq-${version} && mv rocketmq*/* /tmp/rocketmq-${version}
> 
> FROM arm64v8/ubuntu:20.04
> 
> ARG user=rocketmq ARG group=rocketmq ARG uid=3000 ARG gid=3000
> 
> ARG version
> 
> ENV DEBIAN_FRONTEND=noninteractive ENV ROCKETMQ_VERSION ${version} ENV ROCKETMQ_HOME /home/rocketmq/rocketmq-${ROCKETMQ_VERSION} ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64
> 
> EXPOSE 9876 10909 10911 10912
> 
> RUN groupadd -g ${gid} ${group} && useradd -l -u ${uid} -g ${gid} -m -s /bin/bash ${user} && apt-get update && apt-get install -y openjdk-8-jdk less openssl && apt-get clean && rm -rf /var/lib/apt/lists/*
> 
> COPY scripts/ ${ROCKETMQ_HOME}/bin/ COPY --from=builder --chown=${uid}:${gid} /tmp/rocketmq-${version}/ ${ROCKETMQ_HOME}
> 
> RUN mv ${ROCKETMQ_HOME}/bin/runserver-customize.sh ${ROCKETMQ_HOME}/bin/runserver.sh && mv ${ROCKETMQ_HOME}/bin/runbroker-customize.sh ${ROCKETMQ_HOME}/bin/runbroker.sh && chmod -R a+x ${ROCKETMQ_HOME}/bin/ && export JAVA_OPT=" -Duser.home=/opt" && sed -i 's/${JAVA_HOME}/jre/lib/ext/${JAVA_HOME}/jre/lib/ext:${JAVA_HOME}/lib/ext/' ${ROCKETMQ_HOME}/bin/tools.sh && chown -R ${uid}:${gid} ${ROCKETMQ_HOME}
> 
> USER ${user}
> 
> WORKDIR ${ROCKETMQ_HOME}/bin
> 
> ENTRYPOINT ["./docker-entrypoint.sh"] CMD ["dummy"]

thank you very much.❀
