### ISSUE TITLE
Deploy broker with docker-compose returns 253 error

### ISSUE THREAD

**Issue by john1337** [apache/rocketmq-docker#17]
使用下面的配置部署broker，启动报253错误
version: '3.5'
services:
  rmqbroker-a:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker-a
    ports:
      - 11909:10909
      - 11911:10911
      - 11912:10912
    volumes:
      - ./logs/broker-a:/home/rocketmq/logs
      - ./store/broker-a:/home/rocketmq/store
      - ./conf/broker-a/broker-a.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    privileged: true
    command: sh mqbroker -c ../conf/broker.conf autoCreateTopicEnable=true &

配置如下：
brokerClusterName = rocketmq-cluster
brokerName = broker-a
brokerId = 0
# 这个ip配置为内网访问，让mq只能内网访问，不配置默认为内网
#brokerIP1 = 172.21.52.27
deleteWhen = 04
fileReservedTime = 48
# 内网的
namesrvAddr=172.21.52.27:9876
autoCreateTopicEnable=true
#Broker 对外服务的监听端口,
listenPort = 11911
#Broker角色
brokerRole=ASYNC_MASTER
#刷盘方式
flushDiskType=ASYNC_FLUSH

不知哪里出了问题

**Comment by ljjlinjunjie** [comment]
the volumes paths must be **Absolute** ?

**Comment by ljjlinjunjie** [comment]
# RocketMQ is run with user `rocketmq`, uid = 3000
# If you bind mount a volume from the host or a data container,
# ensure you use the same uid
ENSURE that user rocketmq(uid:3000,gid:3000) has rwx permissions to the  derectories of logs and store.

**Comment by cuijianlong** [comment]
$ chown 3000:3000 -R  /xxxx

**Comment by c1ayton** [comment]
你解决这个问题了吗 朋友

**Comment by CrackedSoul** [comment]
挂载路径的权限问题，设置为全可写应该即可。
- ./logs/broker-a:/home/rocketmq/logs
- ./store/broker-a:/home/rocketmq/store

**Comment by yimogit** [comment]
> $ chown 3000:3000 -R /xxxx

Thanks， I use windows, I solve it through it  `sudo chown 3000:3000 -R ./data`

**Comment by wz2cool** [comment]
need disable selinux https://www.linuxprobe.com/disable-selinux.html
