### ISSUE TITLE
How to limited memory by docker-compose ?

### ISSUE THREAD

**Issue by xinghen110** [apache/rocketmq-docker#22]
I start a rocketmq continar with docker-compose.yml for test , and it took 8G memory by default. How should i do to limited memory use to 512M ?

**Comment by aliensb** [comment]
> I start a rocketmq continar with docker-compose.yml for test , and it took 8G memory by default. How should i do to limited memory use to 512M ?

把runserver.sh和runbroker.sh复制到本地来，然后手动修改，之后讲这个文件挂载到容器里面去，替换原有文件。
