### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by marvinguo** [apache/rocketmq-docker#24]
sh build-image.sh 4.4.0 alpine

Version = 4.4.0
Sending build context to Docker daemon 28.16 kB
Step 1/15 : FROM openjdk:8-alpine
 ---> a3562aa0b991
Step 2/15 : RUN apk add --no-cache bash gettext nmap-ncat openssl busybox-extras
 ---> Running in b4b349725631

fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/15) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(2/15) Installing ncurses-terminfo (6.1_p20190105-r0)
(3/15) Installing ncurses-libs (6.1_p20190105-r0)
(4/15) Installing readline (7.0.003-r1)
(5/15) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(6/15) Installing busybox-extras (1.29.3-r10)
Executing busybox-extras-1.29.3-r10.post-install
(7/15) Installing libgomp (8.3.0-r0)
(8/15) Installing libintl (0.19.8.1-r4)
(9/15) Installing libunistring (0.9.10-r0)
(10/15) Installing libxml2 (2.9.9-r2)
(11/15) Installing gettext (0.19.8.1-r4)
(12/15) Installing lua5.3-libs (5.3.5-r2)
(13/15) Installing libpcap (1.9.0-r1)
(14/15) Installing nmap-ncat (7.70-r4)
(15/15) Installing openssl (1.1.1d-r2)
Executing busybox-1.29.3-r10.trigger
OK: 118 MiB in 69 packages
 ---> 02b6d8cd12e2
Removing intermediate container b4b349725631
Step 3/15 : ARG version
 ---> Running in adaf454a9d50
 ---> 105e11f8a06d
Removing intermediate container adaf454a9d50
Step 4/15 : ENV ROCKETMQ_VERSION ${version}
 ---> Running in 530b608589d3
 ---> cc2050818bf1
Removing intermediate container 530b608589d3
Step 5/15 : ENV ROCKETMQ_HOME /home/rocketmq/rocketmq-${ROCKETMQ_VERSION}
 ---> Running in c33d96bf6c65
 ---> 99f05c59460c
Removing intermediate container c33d96bf6c65
Step 6/15 : WORKDIR ${ROCKETMQ_HOME}
 ---> af5a408ef20c
Removing intermediate container d84ddc0708f8
Step 7/15 : RUN set -eux;     apk add --virtual .build-deps curl gnupg unzip;     curl https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip -o rocketmq.zip;     curl https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip.asc -o rocketmq.zip.asc; 	curl https://www.apache.org/dist/rocketmq/KEYS -o KEYS; 		gpg --import KEYS;     gpg --batch --verify rocketmq.zip.asc rocketmq.zip;     unzip rocketmq.zip; 	mv rocketmq-all*/* . ; 	rmdir rocketmq-all* ; 	rm rocketmq.zip rocketmq.zip.asc KEYS; 	apk del .build-deps ;     rm -rf /var/cache/apk/* ;     rm -rf /tmp/*
 ---> Running in cccf01cb11a7

+ apk add --virtual .build-deps curl gnupg unzip
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/20) Installing nghttp2-libs (1.35.1-r1)
(2/20) Installing libssh2 (1.9.0-r1)
(3/20) Installing libcurl (7.64.0-r3)
(4/20) Installing curl (7.64.0-r3)
(5/20) Installing libgpg-error (1.33-r0)
(6/20) Installing libassuan (2.5.1-r0)
(7/20) Installing libcap (2.26-r0)
(8/20) Installing pinentry (1.1.0-r0)
Executing pinentry-1.1.0-r0.post-install
(9/20) Installing libgcrypt (1.8.5-r0)
(10/20) Installing gmp (6.1.2-r1)
(11/20) Installing nettle (3.4.1-r0)
(12/20) Installing gnutls (3.6.7-r0)
(13/20) Installing libksba (1.3.5-r0)
(14/20) Installing db (5.3.28-r1)
(15/20) Installing libsasl (2.1.27-r2)
(16/20) Installing libldap (2.4.48-r0)
(17/20) Installing npth (1.6-r0)
(18/20) Installing gnupg (2.2.19-r0)
(19/20) Installing unzip (6.0-r4)
(20/20) Installing .build-deps (0)
Executing busybox-1.29.3-r10.trigger
OK: 130 MiB in 89 packages
+ curl https://archive.apache.org/dist/rocketmq/4.4.0/rocketmq-all-4.4.0-bin-release.zip -o rocketmq.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.7M  100 11.7M    0     0   3612      0  0:56:47  0:56:46  0:00:01  4335
+ curl https://archive.apache.org/dist/rocketmq/4.4.0/rocketmq-all-4.4.0-bin-release.zip.asc -o rocketmq.zip.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   833  100   833    0     0    190      0  0:00:04  0:00:04 --:--:--   190
+ curl https://www.apache.org/dist/rocketmq/KEYS -o KEYS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   226  100   226    0     0    210      0  0:00:01  0:00:01 --:--:--   210
+ gpg --import KEYS
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
The command '/bin/sh -c set -eux;     apk add --virtual .build-deps curl gnupg unzip;     curl https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip -o rocketmq.zip;     curl https://archive.apache.org/dist/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip.asc -o rocketmq.zip.asc; 	curl https://www.apache.org/dist/rocketmq/KEYS -o KEYS; 		gpg --import KEYS;     gpg --batch --verify rocketmq.zip.asc rocketmq.zip;     unzip rocketmq.zip; 	mv rocketmq-all*/* . ; 	rmdir rocketmq-all* ; 	rm rocketmq.zip rocketmq.zip.asc KEYS; 	apk del .build-deps ;     rm -rf /var/cache/apk/* ;     rm -rf /tmp/*' returned a non-zero code: 2

**Comment by stheart** [comment]
use this url 	curl https://downloads.apache.org/rocketmq/KEYS -o KEYS; \
