### ISSUE TITLE
How to visit each other in HA mode

### ISSUE THREAD

**Issue by luyanfeng** [apache/rocketmq-docker#3]
mac docker做的rocketmq集群（主从），如果我想让docker外部的程序访问 rocketmq，就要配置brokerIP1=docker外部的主机ip。

这虽然是可以让docker外部程序访问rocketmq,但集群内的主从会同步不了，因为slave服务是用的brokerIP1配置的ip访问主服务的。

当然这个也许在linux环境下是可以正常运行的，在mac下需要怎么解决这个问题呢？

**Comment by mrttx** [comment]
你可以考虑一下设置参数brokerIP2

**Comment by liuruiyiyang** [comment]
目前的dockerfile中10912端口没有expose，如果你不是用的start-broker.sh启动的broker可能会存在10912端口无法访问的问题。你可以尝试在dockerfile中EXPOSE 加入10912端口，并重新构建镜像。我们将在近期解决这个问题。感谢你的提问～
