### ISSUE TITLE
Can't run docker with docker centos image

### ISSUE THREAD

**Issue by xwm1992** [apache/rocketmq-docker#33]
I executed the command following the readme, and built the image as below
![image](https://user-images.githubusercontent.com/13237619/108706720-fba6b100-7549-11eb-9625-3b48e51db533.png)
![image](https://user-images.githubusercontent.com/13237619/108707097-85ef1500-754a-11eb-9b2d-fa6e5a71c0ae.png)
then I run `sh play-docker.sh centos` only namesrv can run correctly, docker container will exit for few seconds without any logs.

I try to use alpine image instead, it's ok.

**Comment by zhuchangzhi** [comment]
感谢提供了docker版本，不过弱弱问一下。开发者有测试过这东西能用吗？

**Comment by mask616** [comment]
> 感谢提供了docker版本，不过弱弱问一下。开发者有测试过这东西能用吗？

同问， 按照readme， 一步一个坑。

**Comment by francisoliverlee** [comment]
pls show more details.
as i checked, centos and alpine is OK
![image](https://user-images.githubusercontent.com/5908412/119762028-839cae00-bedf-11eb-94be-205f565dc8a3.png)

**Comment by Frodez** [comment]
> pls show more details.
> as i checked, centos and alpine is OK
> ![image](https://user-images.githubusercontent.com/5908412/119762028-839cae00-bedf-11eb-94be-205f565dc8a3.png)

The problem is that containers can not run successfully, not the images can not be built successfully.
