### ISSUE TITLE
When I execute build-image.sh , Occur '$'\r': command not found' error.

### ISSUE THREAD

**Issue by mask616** [apache/rocketmq-docker#35]
请问现在这个项目现在还有人维护吗？I hava a problem need help。

**Comment by francisoliverlee** [comment]
pls show some details

**Comment by mask616** [comment]
> pls show some details. as i checked, both centos and alpine can run successfully
> ![image](https://user-images.githubusercontent.com/5908412/119761938-5223e280-bedf-11eb-8de6-6805345d33e3.png)

The error info is as follow:
![image](https://user-images.githubusercontent.com/33280931/119766665-0590d500-bee8-11eb-8a93-bdcbb1c6dbbd.png)

And my os version :
![image](https://user-images.githubusercontent.com/33280931/119766836-4ee12480-bee8-11eb-9174-e7ba85422805.png)

**Comment by vongosling** [comment]
Pls try again. also, you could use ./build-image.sh 4.8.0 alphine  or  ./build-image.sh 4.8.0 centos

**Comment by mask616** [comment]
My bad. Because I check out the project at Windos， the I upload to centos. When  I check out at Centos. I build and run successfully.
