### ISSUE TITLE
How does docker limit the heap size of applications in containers ?

### ISSUE THREAD

**Issue by cn-core** [apache/rocketmq-docker#40]
<img width="642" alt="0451d7b035902dc2234d6ee8f1b70e2" src="https://user-images.githubusercontent.com/30290251/131312334-4572e792-7910-4297-95f4-1727f6a5900f.png">

![image](https://user-images.githubusercontent.com/30290251/131312494-7f40b57c-64d4-40eb-a0e3-8a45a9e6ef2c.png)

**Comment by nary24** [comment]
你好，你现在能限制容器内存了吗

**Comment by cn-core** [comment]
@nary24 没有

**Comment by nary24** [comment]
> @nary24 没有
加这个参数可以了，JAVA_OPT_EXT=-Xms128m -Xmx128m -Xmn128m
https://github.com/foxiswho/docker-rocketmq/issues/35
