### ISSUE TITLE
Upload offical latest rocketmq docker image on dockerhub.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/rocketmq-docker#51]
Upload offical latest rocketmq docker image on dockerhub.Why not add `offical` tag for user to choose offical one?
<img width="942" alt="企业微信截图_16461010711860" src="https://user-images.githubusercontent.com/13617900/156092146-5f6b2358-4844-49cb-8f6f-327954ddb4d9.png">

**Comment by GOODBOY008** [comment]
@vongosling Please cc.

**Comment by GOODBOY008** [comment]
I want add `rocketmq` module in `testcontainers`,but `testcontainers` have some requirements on docker images. [testcontainers-issue](https://github.com/testcontainers/testcontainers-java/issues/3348).

**Comment by kinginblue** [comment]
Same confusion, Is there any reason why this repo did'nt release last docker image on dockerhub?

**Comment by duhenglucky** [comment]
@kinginblue @yl-yue 
Official docker repo: https://hub.docker.com/repository/docker/apache/rocketmq

**Comment by duhenglucky** [comment]
> > 
> 
> Thanks for your reply. @duhenglucky Because we search keyword `rocketmq` ,so we are confused.Can `rocketmq` add label ` Official Images` ? ![lQLPDhtB2NJZgrHNA3XNBlaw82P1JV4TYyMCPI6OMoBJAA_1622_885](https://user-images.githubusercontent.com/13617900/159236448-c995f17c-4057-4e47-9c3b-341ea16c9a17.png)

copy

**Comment by ShannonDing** [comment]
link #57 #56

**Comment by caigy** [comment]
link #60 #61
