### ISSUE TITLE
java.lang.UnsatisfiedLinkError: /tmp/jna--518197384/jna1671885036898384730.tmp: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /tmp/jna--518197384/jna1671885036898384730.tmp)

### ISSUE THREAD

**Issue by ldcmd** [apache/rocketmq-docker#81]
The Name Server boot success. serializeType=JSON, address 0.0.0.0:9876
rmqbroker           | java.lang.UnsatisfiedLinkError: /tmp/jna--518197384/jna1671885036898384730.tmp: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /tmp/jna--518197384/jna1671885036898384730.tmp)
rmqbroker           | 	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
rmqbroker           | 	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
rmqbroker           | 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
rmqbroker           | 	at java.lang.Runtime.load0(Runtime.java:809)
rmqbroker           | 	at java.lang.System.load(System.java:1086)
rmqbroker           | 	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:851)
rmqbroker           | 	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
rmqbroker           | 	at com.sun.jna.Native.<clinit>(Native.java:140)
rmqbroker           | 	at org.apache.rocketmq.store.util.LibC.<clinit>(LibC.java:26)
rmqbroker           | 	at org.apache.rocketmq.store.CommitLog$ColdDataCheckService.initPageSize(CommitLog.java:2188)
rmqbroker           | 	at org.apache.rocketmq.store.CommitLog$ColdDataCheckService.<init>(CommitLog.java:2071)
rmqbroker           | 	at org.apache.rocketmq.store.CommitLog.<init>(CommitLog.java:112)
rmqbroker           | 	at org.apache.rocketmq.store.DefaultMessageStore.<init>(DefaultMessageStore.java:221)
rmqbroker           | 	at org.apache.rocketmq.broker.BrokerController.initializeMessageStore(BrokerController.java:749)
rmqbroker           | 	at org.apache.rocketmq.broker.BrokerController.initialize(BrokerController.java:786)
rmqbroker           | 	at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:240)
rmqbroker           | 	at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:50)

**Comment by caigy** [comment]
What's the OS of the image?

**Comment by GenerousMan** [comment]
The alpine image can cause this problem because there is no glibc in it. You can first turn off the broker switch related to cold reading: coldDataFlowControlEnable/ coldDataScanEnable.

Or you can try to use the centos image.

**Comment by caigy** [comment]
I'm closing this issue, but feel free to reopen it if the workaround does not work.
