### ISSUE TITLE
which: command not found

### ISSUE THREAD

**Issue by bradyshi** [apache/rocketmq-docker#82]
/home/rocketmq/rocketmq-5.1.3/bin/runserver.sh: line 34: which: command not found
readlink: missing operand
Try 'readlink --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
ERROR: Please set the JAVA_HOME variable in your environment, We need java(x64)! !!

**Comment by DongyuanPan** [comment]
fix in https://github.com/apache/rocketmq-docker/pull/84
